### ISSUE TITLE
poor performance on custom data

### ISSUE THREAD

**Issue by min-hieu-netropy** [google-research/Splat-SLAM#11]
Hi, I'm trying to run Splat-SLAM on a custom dataset with 2502 1440x1440 images that get resized to 480x480 when I run the demo code. I copy most of he settings from the replica.yaml file but the mapping process still takes around 2 hours. I wonder if there is any tips to resolve this issue?

**Comment by eriksandstroem** [comment]
Hi,
Yes, to be able to manage the memory, the images are downsampled such that dense correlation volumes can be built for optical flow (as in droid-slam and glorie-slam). Regarding runtime, it is highly specific to the hardware. We found that on some local compute resources (where we benchmarked the results in the paper), the runtime was much better than on cluster compute nodes (despite theoretically the same compute capacity). Similar results were reported by the authors of MonoGS, but the root cause is not clear.
