### ISSUE TITLE
Excellent ATE on TUM RGB-D Dynamic Datasets

### ISSUE THREAD

**Issue by jujimeizuo** [google-research/Splat-SLAM#12]
Thanks so much for excellent work!

When I use Splat-SLAM to run on TUM RGB-D Dynamic Datasets such as `walking_xyz`. I got excellent ATE Solution (0.012 m). The same is true for other datasets exclude `walking_static`.

So, do you test Splat-SLAM on dynamic Dataset? And Why does this happen?

Thank you again!

Best Wish!

**Comment by eriksandstroem** [comment]
Hi,
Thanks a lot for your kind comment! We did not test our code on dynamic data and inherently there is no single explanation. I would suppose that the confidence from the optical flow network might yield low confidence scores for dynamic objects (since they can not be matched easily). Therefore, they are down-weighted when estimating the pose and the system thus focuses on the static areas mostly.
