### ISSUE TITLE
visualizing ply and visualization issues

### ISSUE THREAD

**Issue by catchmath** [google-research/Splat-SLAM#14]
Hello,

thanks for the great work.
I'd like to ask a few things.
1) How can I use ply to visualize final results? I got the mesh ply file which can't be visualized like other gs results. I tried to change mesh option to false in the cfg setting but that didn't give me any outputs.
2) how can i see camera trajectory in the map?
3) is there any way to visualize camera trajectory with gs results?

thanks!

**Comment by eriksandstroem** [comment]
Hi!
Thanks, and sorry for the late reply. 

1. Good question. We also save the gs .ply file which can be opened with GS viewers. 
2. The camera trajectory is not overlaid on the map in our visualizations. Is this what you need? We do output the top down view of the trajectory compared to the ground truth though. Did you find this?
3. This would need to be done as a post processing step or I would otherwise suggest using the viewer developed by the authors of MonoGS, which should support this in an online fashion.

Hope this helps!
